### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by just1226** [PaddleCV-SIG/GeoView#26]
作者你好，请问可以借鉴一下你的页面模板吗？

**Comment by yibaikuai** [comment]
这两天我会在我的仓库里新建，供参考

**Comment by just1226** [comment]
能否使用你的代码？并在上面进行改动。

**Comment by just1226** [comment]
> 这两天我会在我的仓库里新建，供参考

能否使用你的代码？并在上面进行改动。

**Comment by yibaikuai** [comment]
可以的

**Comment by yibaikuai** [comment]
> > 这两天我会在我的仓库里新建，供参考
> 
> 能否使用你的代码？并在上面进行改动。

已经上传到我的仓库了哦

**Comment by just1226** [comment]
> > > 这两天我会在我的仓库里新建，供参考
> > 
> > 
> > 能否使用你的代码？并在上面进行改动。
> 
> 已经上传到我的仓库了哦

非常感谢。
