### ISSUE TITLE
关于配置文件格式

### ISSUE THREAD

**Issue by angle011** [PaddleCV-SIG/GeoView#46]
同学 你好，
我想在我的电脑上配置部署Geo-View,但是无法正确加载模型，想询问一下model文件格式和model.yaml格式。（我这边文件目录以及文件名称是否正确，如果方便的话可以发一份正确的文件配置模板吗？211607010047@hhu.edu.cn）
![image](https://user-images.githubusercontent.com/45196429/198519212-f77b7440-3486-41e8-a7cb-669a88d45647.png)

**Comment by yibaikuai** [comment]
已发送

**Comment by angle011** [comment]
感谢 ,hhuer help hhuer

**Comment by terayco** [comment]
> 感谢 ,hhuer help hhuer

不客气，如果还有不清楚地地方的可以看看用户文档哦~，我们会尽快发布用户文档的。

**Comment by Bobholamovic** [comment]
问题已解决，我将关闭这个issue~
