### ISSUE TITLE
项目运行报错

### ISSUE THREAD

**Issue by BoringM** [PaddleCV-SIG/GeoView#63]
你好，请问为什么项目运行起来之后界面都可以正常显示，但是一旦点击【开始处理】之后就会报这个错呢
![image](https://user-images.githubusercontent.com/83158647/227404487-ca07813b-5c80-4963-b920-e5f22b029573.png)

**Comment by jscslld** [comment]
你好，有一些格式的遥感图片需要利用gdal库进行解析。可以参考[GDAL安装教程](https://blog.csdn.net/w259775/article/details/123643956)进行安装。

**Comment by BoringM** [comment]
感谢！问题已经解决！

**Comment by BoringM** [comment]
将pytorch的模型转化为paddle框架下的模型后部署在这个项目中会报错，是因为geoview不支持转化后的模型吗
![image](https://user-images.githubusercontent.com/83158647/228458402-d5b584e6-2fdb-48d1-b701-37002f7820fd.png)

**Comment by jscslld** [comment]
建议您开启debug模式后将控制台的输出贴上来，不然不太好定位具体是哪里的问题

**Comment by BoringM** [comment]
![image](https://user-images.githubusercontent.com/83158647/229388998-c3be56c0-daad-42ce-a2c9-8355f9b4ace报错是这样的，请问可以帮忙看一看是什么问题吗

**Comment by BoringM** [comment]
![image](https://user-images.githubusercontent.com/83158647/229389052-3a4d5e82-8b3b-4619-a02b-6e9c5478f656.png)
报错是这样的请问可以帮忙看看是什么问题吗

**Comment by jscslld** [comment]
参考PaddlePaddle官网，安装适用于GPU的PaddlePaddle
