### ISSUE TITLE
运行app.py时报错:cannot import name 'BaseQuery' from 'flask_sqlalchemy'

### ISSUE THREAD

**Issue by cctx1** [PaddleCV-SIG/GeoView#77]
运行app.py时报错:cannot import name 'BaseQuery' from 'flask_sqlalchemy'，重装flask_sqlchemy仍无效。

![屏幕截图 2023-09-25 113949](https://github.com/PaddleCV-SIG/GeoView/assets/101622840/8a13ba99-ad2a-4f75-af25-4b24bf16f64a)

**Comment by jscslld** [comment]
试试看安装Flask_SQLAlchemy 2.5.1版本，可能是Flask_SQLAlchemy版本太高不兼容。

**Comment by cctx1** [comment]
当使用Flask_SQLAlchemy 2.5.1版本时，出现新的错误，显示SQLAlchemy模块没有__all__属性。
![image](https://github.com/PaddleCV-SIG/GeoView/assets/101622840/cec1b02b-5213-4e1a-9929-0097fa54f0c1)

**Comment by cctx1** [comment]
出现module 'sqlalchemy' has no attribute '__all__'的原因，查询后貌似是因为Flask_SQLAlchemy版本过低的原因，我使用的python版本是3.9.18。

**Comment by cctx1** [comment]
查询flask-sqlalchemy官方文档，flask-sqlalchemy 3.0后的版本BaseQuery属性更名为Query。不知道是不是因为这个的原因。请博主指点。
![image](https://github.com/PaddleCV-SIG/GeoView/assets/101622840/bc6e63dd-5930-454b-b330-ae30b2e90902)

**Comment by jscslld** [comment]
有没有试过把flask_sqlalchemy和sql_alchemy先卸载了重新装指定版本

**Comment by cctx1** [comment]
已经解决了。将Python版本回退到3.7就不报错了。但是在使用的过程中又出现了新的问题。麻烦博主指导一下
