### ISSUE TITLE
使用“地物分类”功能报错

### ISSUE THREAD

**Issue by cctx1** [PaddleCV-SIG/GeoView#78]
如图所示，网页报以下错误：
![image](https://github.com/PaddleCV-SIG/GeoView/assets/101622840/71804bee-67f1-40f8-9c89-0a9514d076e3)

后台输出如下：
![image](https://github.com/PaddleCV-SIG/GeoView/assets/101622840/ab4ffe1c-6411-4c09-8282-9a623134ca13)

**Comment by jscslld** [comment]
![image](https://github.com/PaddleCV-SIG/GeoView/assets/13760010/8753e521-8637-4d90-ac47-5a2446b22674)
把这个use_gpu=True改成False

**Comment by cctx1** [comment]
更改之后仍然报相同的错误。

**Comment by jscslld** [comment]
加我QQ 242123683




卢利栋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddleCV-SIG/GeoView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月30日(星期六) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddleCV-SIG/GeoView] 使用“地物分类”功能报错 (Issue #78)





 
更改之后仍然报相同的错误。

**Comment by jscslld** [comment]
你有试过切换到develop分支吗？

**Comment by jscslld** [comment]
看这个提示，后端推理应该成功了，是前端出现了未捕获的异常。在develop分支上已经修复了这个问题

**Comment by cctx1** [comment]
姗姗来迟，之前使用的确实是0.1版本，刚刚下载了0.1.1的代码，前端运行无误，但是后端运行又报错了(/(ㄒoㄒ)/~~)，如图：
![image](https://github.com/PaddleCV-SIG/GeoView/assets/101622840/dbc1da6c-02fd-4b66-ae69-6c39d1a04601)

刚刚添加了博主的QQ号码，但是没回复我，不知道是不是我输入错了，
头像是
![M8)P$D~~FA4E}@L@J}}BJNP](https://github.com/PaddleCV-SIG/GeoView/assets/101622840/54283e52-565e-4d94-a981-4ac99022fd85)

**Comment by jscslld** [comment]
我QQ 2421235683，重新加下试试
