### ISSUE TITLE
可以看一下作者您这边的依赖版本吗，自己这边因为版本问题跑不起来

### ISSUE THREAD

**Issue by blankanswer** [PaddleCV-SIG/GeoView#86]
可以看一下作者您这边的依赖版本吗，自己这边因为版本问题跑不起来
![image](https://github.com/PaddleCV-SIG/GeoView/assets/97771966/a874bb3a-e998-4d1a-9404-dd6836667904)

**Comment by jscslld** [comment]
麻烦把报错信息截图发上来

**Comment by blankanswer** [comment]
![image](https://github.com/PaddleCV-SIG/GeoView/assets/97771966/5b8c888f-7497-4ef7-9556-eb4bfdf8b575)

**Comment by blankanswer** [comment]
我之前也看了有个issue提到过这个问题，他说退回到python3.7解决了， 我现在已经退回3.7了还是存在这个问题www

**Comment by blankanswer** [comment]
之前那个问题解决了，但是安装paddleRS的时候，它有个很古老的依赖 lap； 这个build不了，不知道是我setuptools太高还是不用用pip install lap；

**Comment by jscslld** [comment]
我印象里这个依赖不安装好像也不影响使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月27日(周二) 晚上9:25
收件人: ***@***.***&gt;;
抄送: "Lu ***@***.******@***.***&gt;;
主题: Re: [PaddleCV-SIG/GeoView] 可以看一下作者您这边的依赖版本吗，自己这边因为版本问题跑不起来 (Issue #86)




 
之前那个问题解决了，但是安装paddleRS的时候，它有个很古老的依赖 lap； 这个build不了，不知道是我setuptools太高还是不用用pip install lap；

**Comment by blankanswer** [comment]
但是不装这个lap的话，他好像paddleRS就都没装上；

![Snipaste_2024-02-27_21-30-13](https://github.com/PaddleCV-SIG/GeoView/assets/97771966/300e765e-05f8-4c47-a2e3-ad2e035bd7ab)

**Comment by jscslld** [comment]
稍等，我明天电脑上试一下再回复您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月27日(周二) 晚上9:31
收件人: ***@***.***&gt;;
抄送: "Lu ***@***.******@***.***&gt;;
主题: Re: [PaddleCV-SIG/GeoView] 可以看一下作者您这边的依赖版本吗，自己这边因为版本问题跑不起来 (Issue #86)




 
但是不装这个lap的话，他好像paddleRS就都没装上；
 
Snipaste_2024-02-27_21-30-13.png (view on web)

**Comment by jscslld** [comment]
这两天测试了一下，你可以用conda先安装好lap，然后再安装paddleRS。
`conda install -c conda-forge lap`

**Comment by blankanswer** [comment]
好嘞好嘞 谢谢谢谢！
