### ISSUE TITLE
安装PaddleRS

### ISSUE THREAD

**Issue by mutou-ship** [PaddleCV-SIG/GeoView#94]
![7ZLP SAPY{7VDDU4_VF89L](https://github.com/PaddleCV-SIG/GeoView/assets/173971056/3822cfb9-2b4c-4bbc-8681-619182cce784)
克隆的PaddleRS文件夹是空的

**Comment by jscslld** [comment]
是不是克隆的时候没有加--recursive

**Comment by mutou-ship** [comment]
![image](https://github.com/PaddleCV-SIG/GeoView/assets/173971056/53c66612-5cde-483e-a541-fa6d24b59b46)
加了的，从
![Uploading 5MGW4]WWLIP}CU}[)]UV`3X.png…]()
下载的文件夹里的Paddle文件里也是空的，没有requirements.txt，只要backend文件夹里有requirements.txt
是下载有误的问题吗

**Comment by jscslld** [comment]
把Geoview文件夹删了以后重新clone。
![image](https://github.com/PaddleCV-SIG/GeoView/assets/13760010/7403d500-d609-4da8-b550-495bdb55e47c)
因为存在Geoview文件夹且非空，所以你执行的clone语句没有生效。

**Comment by mutou-ship** [comment]
上述问题已解决，谢谢
